CFG_SENSORS:
  CPB_BIT_FLIP_DIS: 0
  CPU_ALERT_DIS: 0
  ECC_BIT_FLIP_DIS: 0
  EKDB_BIT_FLIP_DIS: 0
  EM_PULSE_DET_DIS: 0
  GLITCH_DET_DIS: 0
  I_MEM_BIT_FLIP_DIS: 0
  LASER_DET_DIS: 0
  OSCILLATOR_MON_DIS: 0
  PIN_VERIF_BIT_FLIP_DIS: 0
  PLATFORM_BIT_FLIP_DIS: 0
  PTRNG0_TEST_DIS: 0
  PTRNG1_TEST_DIS: 0
  R_MEM_BIT_FLIP_DIS: 0
  SCB_BIT_FLIP_DIS: 0
  SHIELD_DIS: 0
  TEMP_SENS_DIS: 0
  VOLTAGE_MON_DIS: 0
