name: Run tests against TROPIC01 model
on:
  push:
    branches:
      # - 'develop'
      # - 'master'
      - 'integration-tests-action'
  pull_request:
    branches:
      # - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Download ts-tvl wheel
        run: |
          curl -s "https://api.github.com/repos/tropicsquare/ts-tvl/releases/latest" > release.json
          
          WHEEL_URL=$(jq -r '.assets[] | select(.name | endswith(".whl")) | .browser_download_url' release.json)
          if [ -z "$WHEEL_URL" ]; then
            echo "No .whl file found in latest release." >&2
            exit 1
          fi

          WHEEL_FILE_NAME=$(basename "$WHEEL_URL")
          echo "WHEEL_FILE_NAME=$WHEEL_FILE_NAME" >> $GITHUB_ENV
          curl -L -o "$WHEEL_FILE_NAME" "$WHEEL_URL"

      - name: Install dependencies
        run: |
            sudo apt-get install cmake build-essential
            pip install ${{ env.WHEEL_FILE_NAME }}

      - name: Compile libtropic with tests
        run: |
            cd tests/model_based_project/
            cmake ./ -B build -DLT_TEST_CHIP_ID=1
            cd build/
            make
      
      - name: Execute model and run tests
        run: |
            mkdir run_logs/
            model_server tcp > run_logs/model_server.log 2>&1 &
            tests/model_based_project/build/run > run_logs/tests.log 2>&1
      
      - name: Upload run logs
        uses: actions/upload-artifact@v4
        with:
          name: run_logs
          path: run_logs/